---
abstract: 'takes mixed encoding input and produces UTF-8 output'
author:
  - 'Grant McLean <grantm@cpan.org>'
build_requires:
  Test::More: 0.45
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Encoding-FixLatin
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
version: 1.00
